### ISSUE TITLE
归档

### ISSUE THREAD

**Issue by Jackeriss** [Jackeriss/comments_of_www.jackeriss.com#37]
https://www.jackeriss.com/achive 

 Hi, I'm Jackeriss, a Python developer. This blog is written in python using Typora-Blog.

**Comment by footmanFF** [comment]
你的博客是用了云主机搭建的吗

**Comment by Jackeriss** [comment]
嗯，是用云主机搭建的。

**Comment by lifeblood** [comment]
你这个不是放在GIT上的？

**Comment by Jackeriss** [comment]
@lifeblood 不是的，需要服务器。

**Comment by derek-zl** [comment]
你好，我在github上看到，你使用过flask cas 和caravel 做过单点登陆，能给出一个详细的过程说明吗？谢谢，我的邮箱chongchongzl@163.com
